repoURL: 'https://github.com/blangka/devops_k8s'
apps:
  - name: demo
    project: dev
    namespace: default
    source:
      path: demo
  - name: sample-helm-1
    project: dev
    namespace: default
    source:
      path: sample-helm-1
  - name: sample-helm-2
    project: dev
    namespace: default
    source:
      path: sample-helm-2
